README.environ.rst
env.sh.example
mtlpy/api/videos.py
mtlpy/settings.py
mtlpy/templates/videos.html
mtlpy/views.py
requirements.txt
setup.py

Ça va avoir besoin d'une clé d'API dans les settings (probablement via une variable d'environnement en production) qu'on peut générer dans la console de développement Google.

Update video page to use YouTube v3 API

---

Dockerfile
README.md
docker-compose.yml
fixtures/001_users.json

Add a dev setup with docker-compose

---

README.md

Update setup steps and remove cruft in README

---

README.md

Just had the idea that should probably advertise more about our code of conduct

Adds more informations about our code of conduct

---

mtlpy/templates/inc/footer.html

Fix https mixed content in footer

---

mtlpy/templates/base.html
mtlpy/templates/inc/footer.html

Clean up Facebook SDK

---

mtlpy/files.py

Fix debug logic for caching in media view

---

.env.example
mtlpy/settings.py

Add SQL_DEBUG envvar to control DB logs

---

mtlpy/settings.py

Thanks @merwok
@mtlpy/mtlpyweb

Properly remove send-email-on-error Django feature

---

mtlpy/models.py
mtlpy/templates/sponsor_details.html

Fix crash on markup in sponsor detail page

---

Procfile

Run Django migration during release phase of Heroku

---

mtlpy/pages/admin.py
mtlpy/pages/migrations/0002_i18nflatpage_listed.py
mtlpy/pages/models.py
mtlpy/pages/templatetags/i18n_pages.py

The Pycon page must be removed from the website, but we should keep the content somewhere.
This PR adds the option to hide pages from the page navigation links
@merwok @rgeoghegan @hadrien 
#27

Add option to unlist flatpages

---

README.md

Add website link and CircleCi badge in README

---

mtlpy/blog/urls.py
mtlpy/blog/views.py
mtlpy/pages/templatetags/i18n_pages.py
mtlpy/pages/views.py
mtlpy/urls.py
mtlpy/views.py

Remove unused imports

---

mtlpy/templates/inc/footer.html

Add Slack invite link in footer

---

mtlpy/blog/admin.py
mtlpy/pages/admin.py

Fix deprecation about ModelFields fields attributes

---

mtlpy/blog/models.py

Update renamed get_queryset method

---

mtlpy/settings.py

Remove weird Django 1.6 warning based on a random new setting

---

mtlpy/settings.py

Remove deprecated contrib.comments

---

Procfile

Configure gunicorn to use 4 threads

---

.env.example
docker-compose.yml

We are using the ClearDB Addon to provide MySQL.
Ideally the version should be the same... 
@mlhamel

Switch to MySQL in development

---

Dockerfile
mtlpy/templates/inc/footer.html

Add a link to linkedin in footer

---

mtlpy/templates/index.html

Remove duplicate language marker

---

Procfile

@mlhamel Should we clean that right now?

Remove temporary migration mode (--fake-initial)

---

mtlpy/templates/inc/article_list.html

Fix links in article list with double locale marker

---

mtlpy/templates/flatpages/default.html
mtlpy/views.py

- Fix the crash when changing locale
- Can this break something else? @mlhamel

Explicitly pass redirect_to as query-string to change_locale

---

mtlpy/views.py

Fix change_locale crash when trying to rebuild url without route args

---

mtlpy/templates/inc/footer.html

Add simple mailto link to the team email in footer

---

mtlpy/blog/models.py
mtlpy/blog/test_views.py
mtlpy/models.py
mtlpy/templates/article_infos.html

Fix category/sponsor display

---

dev.yml

https://github.com/pior/dad
Ping @mlhamel

Add a dev.yml file for github.com/pior/dad

---

Pipfile
Pipfile.lock

Django-slackin-public changes : https://github.com/mtlpy/django-slackin-public/compare/mtlpy:v0.0.3...v0.1.0

Update django-slackin-public 

---

mtlpy/static/css/components/_sidebar.scss
mtlpy/static/css/style.css

Remove ugly bottom margin in article sidebar

---

mtlpy/templates/base.html

Replace the gtag.js tracker with the analytics.js tracker

---

docs/checklists/presenters.md
docs/presentations.md

Based on https://github.com/montrealelixir/playbook/blob/master/guides/presentations.md
That's really a good idea an I'm gonna also add a presenters guide which we should refer when talking to potentials speakers.

Introduce presentation guide.

---

Pipfile
Pipfile.lock

Next major version changes its API and breaks us

Enforce major version for slackclient

---

mtlpy/templates/inc/footer.html

Pleins d’évènements très cools de planifiés pour 2022. Jettez-y un coup d'oeil!

Updated footer link to the current event calendar
